# Generated by Django 2.2.7 on 2019-11-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matricule',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
