# Generated by Django 2.2.7 on 2019-11-25 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('matricule', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=90)),
                ('email', models.EmailField(max_length=254)),
                ('Group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='actors.Group')),
            ],
        ),
    ]
