# Generated by Django 3.0.1 on 2019-12-30 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iglAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='iglAPI.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='iglAPI.Group'),
        ),
    ]
