# Generated by Django 3.0.1 on 2020-01-02 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iglAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
