# Generated by Django 3.0.1 on 2019-12-31 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iglAPI', '0003_module_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='iglAPI.Student'),
        ),
    ]
