# Generated by Django 3.0.1 on 2019-12-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglAPI', '0004_auto_20191231_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='note',
            field=models.IntegerField(default=0),
        ),
    ]
